import type { Metadata } from "next";
import "animate.css";
import { Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import "../assets/css/oauth.css";
import "../assets/css/modal.css";
import "../assets/css/main.css";
import "../assets/css/custom.css";
import "../assets/css/modern.css";
import { Providers } from "@/store/provider";
import AllModals from "@/modals/AllModals";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <Providers>
          <>
            {children} <AllModals />
          </>
        </Providers>
      </body>
    </html>
  );
}
